language: node_js
 node_js:
 - 0.8
 - 0.10
 before_install:
 - npm install -g dredd
 script: ./validate.sh
 services:
 - mongodb
 before_script:
 - mongo mydb_test --eval 'db.addUser("test", "test");'